apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage-mongo
  local:
    path: /mnt/disk/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In 
          values:
          - prod
