apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: external
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-storage-mongo
