# Mongo secrets
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: ZGV2b3Bz
  password: RGJwODk5am9wd2JqRVZLYVJEcm10Sw==
  url: bW9uZ28uZXh0ZXJuYWwuc3ZjLmNsdXN0ZXIubG9jYWw=
